services:
  - type: web
    name: ileaf-luxury-backend
    env: node
    plan: free
    region: singapore # Changed to singapore for faster latency in Thailand
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
